# Generated by Django 4.2.3 on 2023-07-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myprofile",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="myapi.avataruser",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="myprofile",
            name="phone",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
